name: nodejs-todo-s7
services:
  nodejs-todo-mongo:
    restart: always
    build: ../../NodeJS/ToDoNodeJS-MongoDB
    environment:
      - DB_URL=mongodb
      - DB_NAME=test
    links:
      - mongodb
    expose:
      - "3000"
  nodejs-todo-mysql:
      restart: always
      build: ../../NodeJS/ToDoNodeJS-MySQL
      environment:
        - DB_HOST=mysqldb
        - DB_USER=test
        - DB_PASSWORD=test
        - DB_NAME=test
      depends_on:
          mysqldb:
            condition: service_healthy
            restart: true
      expose:
        - "3000"
  reverse-proxy:
    image: nginx:latest
    links:
      - nodejs-todo-mysql
      - nodejs-todo-mongo
    volumes:
      - ./nodejs-todo.conf:/etc/nginx/conf.d/default.conf    
    expose:
      - "80" 
    ports:
      - "8080:80" 
  mongodb:
    image: mongo:5.0.27
    expose:
      - "27017"
    volumes:
      - mongodb-vol:/var/lib/mysql
  mysqldb:
    image: mysql:lts
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    command: --mysql_native_password=ON --init-file /data/application/init.sql
    expose:
      - "3306"
    volumes:
      - mysqldb-vol:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
volumes:
  mysqldb-vol:
    external: false
  mongodb-vol:
    external: false
  
